### ISSUE TITLE
st_drop_geometry

### ISSUE THREAD

**Issue by ratnanil** [dionisanderegg/cma-week2#2]
https://github.com/dionisanderegg/cma-week2/blob/10120028c3d23252dfd78f2edc8497a67b5e21a5/cma-week2.R#L39-L41<br/><br/>You might have noticed that this operation makes a `multipoint` object out of the wildboar locations. If you want to avoid this in the future (this operation might take a long time), simply use `st_drop_geometry` like so:

```
wildschwein_BE_group <- wildschwein_BE %>%
  st_drop_geometry() %>%
  group_by(timelag_round) %>%
  summarise(n = n())
```

**Comment by dionisanderegg** [comment]
Thanks for the hint.
Solved, committed "solved issue 2".
