### ISSUE TITLE
facetting

### ISSUE THREAD

**Issue by ratnanil** [dionisanderegg/cma-week2#3]
https://github.com/dionisanderegg/cma-week2/blob/10120028c3d23252dfd78f2edc8497a67b5e21a5/cma-week2.R#L62-L66<br/><br/>I think you already know this functionality, but in case you dont:

If your data is poorly visible because the points are overplotting, you can facet it into different subplots using `facet_wrap()`

```
wildschwein_BE %>%
  ggplot(aes(DatetimeUTC, timelag, col = TierName)) +
  geom_point() +
  geom_line () +
  theme_bw() +
  facet_wrap(~TierName)
```

**Comment by dionisanderegg** [comment]
Solved. Committed "solved issue #3"
